# Generated by Django 5.2.7 on 2025-10-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='issueevent',
            old_name='action',
            new_name='event_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='sla_due_at',
        ),
        migrations.RemoveField(
            model_name='issueevent',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='issueevent',
            name='from_value',
        ),
        migrations.RemoveField(
            model_name='issueevent',
            name='note',
        ),
        migrations.RemoveField(
            model_name='issueevent',
            name='to_value',
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default='Unnamed Asset', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asset'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.CharField(default='Unassigned', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name'], name='core_asset_name_9b3471_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project'], name='core_asset_project_8ecf57_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['issue'], name='core_attach_issue_i_aad220_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['created_at'], name='core_attach_created_d54bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='core_issue_status_2609e6_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['updated_at'], name='core_issue_updated_1db01c_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'status'], name='core_issue_project_6f4828_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['asset', 'status'], name='core_issue_asset_i_eb0cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='core_projec_name_0563a9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['updated_at'], name='core_projec_updated_d4a6ea_idx'),
        ),
    ]
